// <auto-generated />
namespace SIPI.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Orador_MediosAudiovisual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Orador_MediosAudiovisual));
        
        string IMigrationMetadata.Id
        {
            get { return "201707171926586_Orador_MediosAudiovisual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
