// <auto-generated />
namespace SIPI.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Miembro_Remove_Direccion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Miembro_Remove_Direccion));
        
        string IMigrationMetadata.Id
        {
            get { return "201707152254516_Miembro_Remove_Direccion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
